# Generated by Django 4.2.27 on 2026-01-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0004_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
