# Generated by Django 4.2.27 on 2026-01-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0006_alter_recipe_created_at_alter_recipe_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
