# Generated by Django 4.2.27 on 2026-01-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0007_alter_recipe_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height_cm',
            field=models.FloatField(blank=True, help_text='Height in centimeters', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight_kg',
            field=models.FloatField(blank=True, help_text='Weight in kilograms', null=True),
        ),
    ]
