# Generated by Django 4.2.27 on 2026-01-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0009_mealplan_userprofile_meal_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='meal_plan',
        ),
    ]
