# Generated by Django 4.2.27 on 2026-01-16 21:45

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0011_userprofile_meal_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='meal_plan',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_image',
            field=cloudinary.models.CloudinaryField(default='default_profile', max_length=255, verbose_name='image'),
        ),
    ]
