# Generated by Django 4.2.27 on 2026-01-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0012_remove_userprofile_meal_plan_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(help_text='List of ingredients with quantities in JSON format'),
        ),
    ]
