# Generated by Django 4.2.27 on 2026-01-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0013_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='fiber',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
