# Generated by Django 4.2.27 on 2026-01-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0014_recipe_fiber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(help_text='List of ingredients with quantities in JSON format'),
        ),
    ]
