# Generated by Django 4.2.27 on 2026-01-20 12:27

import cloudinary.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0015_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=cloudinary.models.CloudinaryField(
                default='default.jpg', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(
                default=list, help_text='List of ingredients with quantity and unit. Format: [{"name": "Flour", "quantity": "2.5 for 2 1/2" , "unit": "cup"}, ...]'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(
                max_length=500), blank=True, default=list, size=None),
        ),
    ]
