# Generated by Django 4.2.27 on 2026-01-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0017_alter_recipe_category_alter_recipe_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(help_text='List of ingredients with quantity and unit. Format: 2 cups of rice, 1 tbsp olive oil, etc.'),
        ),
    ]
