# Generated by Django 4.2.27 on 2026-01-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0018_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(help_text='e.g. 2 cups of rice, 1 tbsp olive oil, etc.'),
        ),
    ]
